Missing items report for metadb
metadb-project/metadb-examples pull request #1
Opened 2023-11-13 21:56 UTC by hutchinsonca

I've created a generic query to look for missing items and output the data needed to search the stacks.

2023-11-14 00:03 UTC, nassibnassar requested changes

2023-11-14 00:03 UTC, nassibnassar commented on folio/reports/missing_items.sql
> +CREATE FUNCTION missing_items
First of all, if the function has no parameters, this line should be
```
CREATE FUNCTION missing_items()
```

That is not the only error.

The function should be tested before submitting a pull request.

2023-11-14 15:45 UTC, hutchinsonca commented on folio/reports/missing_items.sql
> +CREATE FUNCTION missing_items
I updated missing_items.sql and ran it successfully in DBeaver.

2023-11-15 01:04 UTC, nassibnassar approved these changes

2023-11-15 01:04 UTC, merged

2023-11-15 01:08 UTC, nassibnassar commented on folio/reports/missing_items.sql
> +-- metadb:function missing_items
There should not be a space after the `--`.  I will fix this and also adjust the SQL formatting.